### ISSUE TITLE
getApplicationContext returns a context with the wrong resources

### ISSUE THREAD

**Issue by j05u3** [zeugma-solutions/locale-helper-android#1]
In many parts of my application we use the application context to get string resources. So after changing the locale: the string resources obtained from the application context were still loaded from the previous locale. Those strings were only correctly updated after re-opening the app.

I even tried using a ContextWrapper as mentioned [here](https://stackoverflow.com/a/46939076/2469583) but it didn't work.

Target SDK: 28.
My tests were done on a emulator with android API 24.

I couldn't implement a fix, so we ended up just using the activity context (which works fine) to get the string resources.

**Comment by gunhansancar** [comment]
Can you share more context to the problem? E.g Do you have DI provider and you initialise your string resource manager with the application context and provide that to your viewmodels? Or why are you using application context for strings? If you can share an example usage I can take a look at potential solution.

**Comment by j05u3** [comment]
I already fixed that app. But I do have another android app (which very probably will require the language changer feature) in which I use the application object injected with dagger to the viewmodels and sometimes I use that context to get resources for Toasts. I know I should be using livedata for displaying the Toast, but it seems like a lot more code to add for just a simple thing.

**Comment by gunhansancar** [comment]
So I dig into the issue but It looks like application context is not properly updated after API 24. Even though it returns the correct locale, when it is time to get the resource it uses the initial context.

Only way I found working is when you update the language, you let to know the `StringManager` to update its context by using the `LocaleHelper.onAttach(context)` and providing the application context(initially). Then it keeps the reference of this new localized context.

E.g from the sample:
```
override fun updateLocale(locale: Locale) {
        super.updateLocale(locale)
        (application as Application).stringResource.update()
        setTitle(R.string.main_activity_title)
    }
```
And the String manager
```
class StringResource(var context: Context) {

    fun update() {
        context = LocaleHelper.onAttach(context)
    }

    fun string(resId: Int): String {
        return context.getString(resId)
    }
} 
```

This implementation is not the part of the library and I can't think this problem can be solved directly inside the library. So I'm considering closing the issue but will wait for your comment as well.
