### ISSUE TITLE
conflict with AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM

### ISSUE THREAD

**Issue by AhmedSaadShrief** [zeugma-solutions/locale-helper-android#12]
when usings LocaleAwareApplication() instead of Application() , 
AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM  don't work correctly .

**Comment by AlexSheva-mason** [comment]
I can confirm that as well, just checked.

**Comment by gunhansancar** [comment]
Released `v1.0.4` version with the with for the `uimode` issues. 
In the sample project I added dark mode support and it seems working for all versions of Android so far. 
Please check the new version and let me know if it fixes the issue

**Comment by gunhansancar** [comment]
Closing due to no response. If the changes not helpful please create a new ticket.

**Comment by Alireza-Farahani** [comment]
Using version 1.1.4, I face the same issue.

**Comment by gunhansancar** [comment]
@Alireza-Farahani did you try the sample project, as it works there?

**Comment by Alireza-Farahani** [comment]
@gunhansancar I tried the sample and I can manually toggle dark/light with success but enabling dark mode through system settings doesn't affect the sample.

**Comment by gunhansancar** [comment]
This could be related to #32 So let's continue on that ticket
