### ISSUE TITLE
Khmer Language Not Working

### ISSUE THREAD

**Issue by bhargavsavasani** [zeugma-solutions/locale-helper-android#13]
This Library in Khmer (Cambodia) Language not Working

**Comment by gunhansancar** [comment]
Hi @BhargavSavasani What do you mean by not working?

What did you try and what did you expect to happen? 

You should provide more information so that we can better understand the issue.

**Comment by bhargavsavasani** [comment]
@gunhansancar 
Sorry for late replay 
My Side Working Now
