### ISSUE TITLE
Multiple/Nested base activity

### ISSUE THREAD

**Issue by nishantBabaria** [zeugma-solutions/locale-helper-android#17]
hi
it's a good example for a  local language

but why use multiple/nested base activity 
LocaleAwareCompatActivity > BaseActivity > MainActivity
I think it good approach that keeps one base activity but nested base activity cause memory /performance issue

please correct me if I'm wrong
thanks

**Comment by gunhansancar** [comment]
Hi,

Inheritance would not cause any memory/performance problems at all.

You can also opt-out to not use `LocaleAwareCompatActivity` and implement the delegate methods by yourself. For instance if you have another base activity then it is valid case to implement delegate methods but other than that there is no performance issue whatsoever.
