### ISSUE TITLE
Doesnt work on Android 10

### ISSUE THREAD

**Issue by WeaponMan** [zeugma-solutions/locale-helper-android#21]
Sadly it doesnt work on Android 10 Nokia 6.1.
First language change is succesfull, but if you exit the app an launch it again it doesnt stay in that language and after that you can change the language to another but it stays in the locale of your device.

Maybe this is problem with MultiDex?

**Comment by gunhansancar** [comment]
Hi @WeaponMan , Could you try version `1.1.0` as it works for all versions of android if you use `appcompat` version `1.2.0`

**Comment by gunhansancar** [comment]
Please reopen if the version `1.1.0` doesn't work on your case.
