### ISSUE TITLE
Locale helper for non Activity contexts

### ISSUE THREAD

**Issue by thubalek** [zeugma-solutions/locale-helper-android#23]
My app is using notifications fired from services so settings set to `LocaleHelper` should be somehow propagated to `Service`'s too. 

Any idea?

**Comment by gunhansancar** [comment]
In your `Service` override the `attachBaseContext` method

```
override fun attachBaseContext(base: Context) {
        super.attachBaseContext(LocaleHelper.onAttach(base))
}
```

After that point, you will get the updated resources in your `Service`
