### ISSUE TITLE
Override ApplicationContext.

### ISSUE THREAD

**Issue by Dobrotin** [zeugma-solutions/locale-helper-android#24]
"getApplicationContext" return ContextImpl instead Application.
Cause: context.createConfigurationContext(configuration) from LocaleHelper.

English is not my native language, so please be kind to my mistakes.

**Comment by gunhansancar** [comment]
Hi, In which version did you get this error?

**Comment by Dobrotin** [comment]
Hi! Version - 1.1.0.
The problem is with the conversion of ApplicationContext to ContextImpl, as the context.createConfigurationContext (configuration) method is used.

**Comment by gunhansancar** [comment]
What android version you're using and at what point did you get this? I tested the library on all versions. It is really interesting.

**Comment by Dobrotin** [comment]
Android 10.
Try to get your instance of Application from ApplicationContext in the Activity code (example: applicationContext as MyApplication).

**Comment by Dobrotin** [comment]
Thx! )

**Comment by gunhansancar** [comment]
Released 1.1.1 to address this issue.
