### ISSUE TITLE
Not working GoogleMap (MapView).

### ISSUE THREAD

**Issue by Dobrotin** [zeugma-solutions/locale-helper-android#25]
MapView crashes on initialization: "The provided context is not an application context".
If comment out the line of LocaleAwareApplication: getApplicationContext() - MapView work fine.

**Comment by gunhansancar** [comment]
Could be related to #24 Please try with version `1.1.1`

**Comment by Dobrotin** [comment]
Yes, I immediately took the current version.
The problem is present in it (1.1.1).

**Comment by mfori** [comment]
same here

**Comment by gunhansancar** [comment]
Why would you give application context to mapview? It is supposed to be the activity context. 
Could you share your initialization example?

**Comment by mfori** [comment]
for me, it occurs at:
`mapView.onCreate(savedInstanceState);`
So i dont pass any context, mapview is inflated from layout

**Comment by gunhansancar** [comment]
Are you using this one `https://developers.google.com/maps/documentation/android-sdk/start` Map Fragment? Or something else?

**Comment by mfori** [comment]
I am also fancing this issue on start app if I use LocaleAwareApplication. If I use just android.app.Application it works and also localization works with only extending all activities.

`2020-09-26 10:13:44.552 9215-9238/cz.app.name E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cz.app.name, PID: 9215
    java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Application
        at com.google.android.gms.internal.measurement.zzag.<init>(com.google.android.gms:play-services-measurement-sdk-api@@17.5.0:37)
        at com.google.android.gms.internal.measurement.zzag.zza(com.google.android.gms:play-services-measurement-sdk-api@@17.5.0:6)
        at com.google.android.gms.measurement.api.AppMeasurementSdk.getInstance(com.google.android.gms:play-services-measurement-sdk-api@@17.5.0:2)
        at com.google.android.gms.internal.ads.zzamt.zze(com.google.android.gms:play-services-ads-lite@@19.4.0:41)
        at com.google.android.gms.internal.ads.zzamw.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by gunhansancar** [comment]
Yes, for some versions of Android API it works without `LocaleAwareApplication` but for some other versions the localisation doesn't work. So it is needed to cover all Android API levels. Thus, it is better to find the root cause of this issue.

**Comment by mfori** [comment]
> Are you using this one `https://developers.google.com/maps/documentation/android-sdk/start` Map Fragment? Or something else?

No, in this case, I am using MapView inside fragment: https://developers.google.com/android/reference/com/google/android/gms/maps/MapView

**Comment by gunhansancar** [comment]
For the time being my suggestion is to continue without the `LocaleAwareApplication` I aim to fix the issue later on today 🤞

**Comment by gunhansancar** [comment]
Released `1.1.2` also please use `LocaleAwareApplication` or its delegate in your custom `Application` class.
