### ISSUE TITLE
Problem setting theme

### ISSUE THREAD

**Issue by dzboot02** [zeugma-solutions/locale-helper-android#29]
```
class MainActivity: AppCompatActivity() {
      override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(savedInstanceState)
      localeDelegate.onCreate(this)
      setTheme(R.style.AppTheme_Main)
      setContentView(binding.root)
   }
}
```

Setting the theme this way won't work. Theme needs to be set set before `localeDelegate.onCreate(this)`.

**Comment by gunhansancar** [comment]
How about you set the theme before `super.onCreate` is called i.e.:
```
override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style. AppTheme_Main)
        super.onCreate(savedInstanceState)
}
```
In my tests, it works this way

**Comment by dzboot02** [comment]
@gunhansancar Yes I know, I mentioned this in my original question. I mean this should be taken care in the library, or at least mention it in the docs.

**Comment by gunhansancar** [comment]
I need to check if it affects any version in any configuration to change the order of the code. Then I'll release an update for that. Thanks for your notice.
