### ISSUE TITLE
Usage in BroadcastReceiver

### ISSUE THREAD

**Issue by JulienDev** [zeugma-solutions/locale-helper-android#31]
Hello,

I'd like to know if there is a way to make it working inside BroadcastReceiver. I display notifications from a custom BroadcastReceiver but the locale is wrong. The content are not translated following the user settings.

For now I'm using `context.applicationContext` in the onReceive() function but it only works when the app has been killed after language selection.

Thanks

**Comment by gunhansancar** [comment]
You can wrap any context object using
`LocaleHelper.onAttach(context)` which returns Context with updated resources. 
Then you can use it as you like.

**Comment by JulienDev** [comment]
Ok I got it, thank you :)
