### ISSUE TITLE
JCenter will be completely shut down February 1, 2022

### ISSUE THREAD

**Issue by YYwishp** [zeugma-solutions/locale-helper-android#39]
JCenter will be completely shut down February 1, 2022 ，please update to Maven Central

**Comment by gunhansancar** [comment]
@YYwishp Thank you for letting me know. I will try to move it directly to Maven Central in the next versions. I hope the transition would be easy.

**Comment by altagir** [comment]
Any progress?

**Comment by yoobi** [comment]
Hello, any news ? February is closing in :)

**Comment by Berki2021** [comment]
Any progress??

**Comment by gunhansancar** [comment]
I published here on main maven repository 
https://repo1.maven.org/maven2/com/zeugmasolutions/localehelper/locale-helper-android/
Could you check that if that works?

**Comment by Berki2021** [comment]
> I published here on main maven repository https://repo1.maven.org/maven2/com/zeugmasolutions/localehelper/locale-helper-android/ Could you check that if that works?

Yes it does, although you could have mentioned that you bumped up the version from 1.1.4 to 1.5.1 :)

**Comment by gunhansancar** [comment]
README file will be updated soon

**Comment by yoobi** [comment]
Thank you for the update ! Is there any change in the lib ? Is it just the change to maven central ?

**Comment by gunhansancar** [comment]
@yoobi It is still the same version. I bumped the version just to separate them easily from old and new repos.
Just one difference is that I bumped the dependency versions in the lib e.g. `appcompat` version to the latest.

I will try to address the other issues then make a new version. 
So closing this issue.
If you have any concerns feel free to create a new issue.
