### ISSUE TITLE
updateLocale(); from main activity doesnt work on Android 7 and below

### ISSUE THREAD

**Issue by Akshshr** [zeugma-solutions/locale-helper-android#4]
Calling updateLocale() from the mainActivity which is called its baseActivity, this doesn't seem to change the locale on Android 7 and 6. 

Running this in loop shows no new locale was added or updated

`       
Locale locale = this.getResources().getConfiguration().locale; //Always shows the same even after updating
                 
String languageGW = //Language code derived from backend
String phoneLocale = locale.toLanguageTag();

 if(languageGW != null && !phoneLocale.equals(languageGW)){
//Change language now, discrepancy found between backend and local phone language
updateLocale(Locale.forLanguageTag(languageGW)); 

}

`

**Comment by gunhansancar** [comment]
After the locale is updated you have to refresh the resources on the screen. So just calling updateLocale is not enough. 
You can let the library handle activity recreation or you can handle yourself.

This library/code is being used in multiple production apps and it works on all of the Android versions as of yet. 

If you can provide a sample project, I can take a look it and tell you what step you're missing and give you a better answer.

You can download the example project on this repo and test it on Android 6.0 -7.0 device.

**Comment by Akshshr** [comment]
@gunhansancar Yes calling a rebirth method for the entire app that cleans out the cache and rebuilds all activities after changing language. Still having no luck on it


I could perhaps build a demo project

**Comment by Akshshr** [comment]
@gunhansancar Yup, seeing this not do anything on Android 6.0 for sure
 `
String languageGW = "sv-SE"; 
updateLocale(Locale.forLanguageTag(languageGW));`

Can this be verified on your end?

**Comment by gunhansancar** [comment]
Do you have a folder called `values-sv-rSE` in your `main/res/` directory?

**Comment by Akshshr** [comment]
I do have `values-sv`

**Comment by gunhansancar** [comment]
It should work with `values-sv` folder as well.

I added Swedish to the example project and it works on the simulator on Android 7.0. Also tested on Android 5.0 it is still working. I can add another AVD for 6.0 but I'm sure the result would be the same. 

```
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            val languageGW = "sv-SE"
            val swedish = Locale.forLanguageTag(languageGW)
            toSVButton.setOnClickListener { updateLocale(swedish) }
        }
```

**Comment by codeItRalf** [comment]
I have a similar problem, trying figuring what it can be because it has worked on all versions. But now for some reason, it doesn't work on 7.0 - 7.1.
It still works on all other versions from 5.1 to 10.0.

My main device is 7.1 and just someday ago I can swear it worked and I cant remember I have done any changes which are very annoying. It doesn't update the text, but if I choose Arabic it changes to LTR layout but not the text.

Have any clues about what it can be? 

If you want to see it in action check my app
https://play.google.com/store/apps/details?id=com.codeitralf.verbmate&hl=en
Just go to settings and change language works with all versions except 7.0 and 7.1.

**Comment by codeItRalf** [comment]
I had almost the same problem. But I knew it had worked before but for some reason, it stopped working for 7.0 -7.1.
I didn't remember that I had done any changes, it wasn't until I tried out the sample app and I updated the Gradle dependencies then I had the same problem. 
I hope this helps for anyone else, change these dependencies to following.

implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.preference:preference:1.1.0-rc01'

Now it works like a charm! :)

**Comment by gunhansancar** [comment]
@codeItRalf Yes, it seems there is an issue for  [androidx.appcompat v1.1.0](https://stackoverflow.com/questions/55265834/change-locale-not-work-after-migrate-to-androidx)

**Comment by jershell** [comment]
I have this problem too. I use the solution https://stackoverflow.com/a/58004553/3751051. It's working.

**Comment by nuwanchamara** [comment]
> I have this problem too. I use the solution https://stackoverflow.com/a/58004553/3751051. It's working.

It works. Thanks @jershell  for the answer. I Used [https://stackoverflow.com/a/58004553/3751051](https://stackoverflow.com/a/58004553/3751051) answer . You have to do is add the following code to your BaseActivity class

```
override fun applyOverrideConfiguration(overrideConfiguration: Configuration?) {
    if (overrideConfiguration != null) {
        val uiMode = overrideConfiguration.uiMode
        overrideConfiguration.setTo(baseContext.resources.configuration)
        overrideConfiguration.uiMode = uiMode
    }
    super.applyOverrideConfiguration(overrideConfiguration)
}
```

**Comment by nuwanchamara** [comment]
the above solution is not working for `R.string.mystring` in XML (API level 29)
